/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.herocheer.zhsq.localservice.core.device.box.YTBox.pojo;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Image extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6699952776591391713L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Image\",\"namespace\":\"com.herocheer.zhsq.localservice.core.device.box.YTBox.pojo\",\"fields\":[{\"name\":\"content\",\"type\":\"bytes\"},{\"name\":\"content_type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"valid mime-type\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.nio.ByteBuffer content;
  /** valid mime-type */
  @Deprecated public String content_type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Image() {}

  /**
   * All-args constructor.
   * @param content The new value for content
   * @param content_type valid mime-type
   */
  public Image(java.nio.ByteBuffer content, String content_type) {
    this.content = content;
    this.content_type = content_type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return content;
    case 1: return content_type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: content = (java.nio.ByteBuffer)value$; break;
    case 1: content_type = (String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.nio.ByteBuffer getContent() {
    return content;
  }

  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.nio.ByteBuffer value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'content_type' field.
   * @return valid mime-type
   */
  public String getContentType() {
    return content_type;
  }

  /**
   * Sets the value of the 'content_type' field.
   * valid mime-type
   * @param value the value to set.
   */
  public void setContentType(String value) {
    this.content_type = value;
  }

  /**
   * Creates a new Image RecordBuilder.
   * @return A new Image RecordBuilder
   */
  public static Image.Builder newBuilder() {
    return new Image.Builder();
  }

  /**
   * Creates a new Image RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Image RecordBuilder
   */
  public static Image.Builder newBuilder(Image.Builder other) {
    return new Image.Builder(other);
  }

  /**
   * Creates a new Image RecordBuilder by copying an existing Image instance.
   * @param other The existing instance to copy.
   * @return A new Image RecordBuilder
   */
  public static Image.Builder newBuilder(Image other) {
    return new Image.Builder(other);
  }

  /**
   * RecordBuilder for Image instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Image>
    implements org.apache.avro.data.RecordBuilder<Image> {

    private java.nio.ByteBuffer content;
    /** valid mime-type */
    private String content_type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Image.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.content)) {
        this.content = data().deepCopy(fields()[0].schema(), other.content);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content_type)) {
        this.content_type = data().deepCopy(fields()[1].schema(), other.content_type);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Image instance
     * @param other The existing instance to copy.
     */
    private Builder(Image other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.content)) {
        this.content = data().deepCopy(fields()[0].schema(), other.content);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content_type)) {
        this.content_type = data().deepCopy(fields()[1].schema(), other.content_type);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getContent() {
      return content;
    }

    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public Image.Builder setContent(java.nio.ByteBuffer value) {
      validate(fields()[0], value);
      this.content = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public Image.Builder clearContent() {
      content = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'content_type' field.
      * valid mime-type
      * @return The value.
      */
    public String getContentType() {
      return content_type;
    }

    /**
      * Sets the value of the 'content_type' field.
      * valid mime-type
      * @param value The value of 'content_type'.
      * @return This builder.
      */
    public Image.Builder setContentType(String value) {
      validate(fields()[1], value);
      this.content_type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'content_type' field has been set.
      * valid mime-type
      * @return True if the 'content_type' field has been set, false otherwise.
      */
    public boolean hasContentType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'content_type' field.
      * valid mime-type
      * @return This builder.
      */
    public Image.Builder clearContentType() {
      content_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Image build() {
      try {
        Image record = new Image();
        record.content = fieldSetFlags()[0] ? this.content : (java.nio.ByteBuffer) defaultValue(fields()[0]);
        record.content_type = fieldSetFlags()[1] ? this.content_type : (String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
