/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.herocheer.zhsq.localservice.core.device.box.YTBox.pojo;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ResultType {
  Capture, Retrieval  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ResultType\",\"namespace\":\"com.herocheer.zhsq.localservice.core.device.box.YTBox.pojo\",\"symbols\":[\"Capture\",\"Retrieval\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
