/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.herocheer.zhsq.localservice.core.device.box.YTBox.pojo;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RetrievalResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8805976011192550476L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RetrievalResult\",\"namespace\":\"com.herocheer.zhsq.localservice.core.device.box.YTBox.pojo\",\"fields\":[{\"name\":\"repository_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"similar_faces\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SimilarFace\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"face_id in the repository\"},{\"name\":\"similarity\",\"type\":\"double\",\"doc\":\"0 - 100\"},{\"name\":\"extra_meta\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"json format\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public String repository_id;
  @Deprecated public java.util.List<SimilarFace> similar_faces;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RetrievalResult() {}

  /**
   * All-args constructor.
   * @param repository_id The new value for repository_id
   * @param similar_faces The new value for similar_faces
   */
  public RetrievalResult(String repository_id, java.util.List<SimilarFace> similar_faces) {
    this.repository_id = repository_id;
    this.similar_faces = similar_faces;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return repository_id;
    case 1: return similar_faces;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: repository_id = (String)value$; break;
    case 1: similar_faces = (java.util.List<SimilarFace>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'repository_id' field.
   * @return The value of the 'repository_id' field.
   */
  public String getRepositoryId() {
    return repository_id;
  }

  /**
   * Sets the value of the 'repository_id' field.
   * @param value the value to set.
   */
  public void setRepositoryId(String value) {
    this.repository_id = value;
  }

  /**
   * Gets the value of the 'similar_faces' field.
   * @return The value of the 'similar_faces' field.
   */
  public java.util.List<SimilarFace> getSimilarFaces() {
    return similar_faces;
  }

  /**
   * Sets the value of the 'similar_faces' field.
   * @param value the value to set.
   */
  public void setSimilarFaces(java.util.List<SimilarFace> value) {
    this.similar_faces = value;
  }

  /**
   * Creates a new RetrievalResult RecordBuilder.
   * @return A new RetrievalResult RecordBuilder
   */
  public static RetrievalResult.Builder newBuilder() {
    return new RetrievalResult.Builder();
  }

  /**
   * Creates a new RetrievalResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RetrievalResult RecordBuilder
   */
  public static RetrievalResult.Builder newBuilder(RetrievalResult.Builder other) {
    return new RetrievalResult.Builder(other);
  }

  /**
   * Creates a new RetrievalResult RecordBuilder by copying an existing RetrievalResult instance.
   * @param other The existing instance to copy.
   * @return A new RetrievalResult RecordBuilder
   */
  public static RetrievalResult.Builder newBuilder(RetrievalResult other) {
    return new RetrievalResult.Builder(other);
  }

  /**
   * RecordBuilder for RetrievalResult instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RetrievalResult>
    implements org.apache.avro.data.RecordBuilder<RetrievalResult> {

    private String repository_id;
    private java.util.List<SimilarFace> similar_faces;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(RetrievalResult.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.repository_id)) {
        this.repository_id = data().deepCopy(fields()[0].schema(), other.repository_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.similar_faces)) {
        this.similar_faces = data().deepCopy(fields()[1].schema(), other.similar_faces);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RetrievalResult instance
     * @param other The existing instance to copy.
     */
    private Builder(RetrievalResult other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.repository_id)) {
        this.repository_id = data().deepCopy(fields()[0].schema(), other.repository_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.similar_faces)) {
        this.similar_faces = data().deepCopy(fields()[1].schema(), other.similar_faces);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'repository_id' field.
      * @return The value.
      */
    public String getRepositoryId() {
      return repository_id;
    }

    /**
      * Sets the value of the 'repository_id' field.
      * @param value The value of 'repository_id'.
      * @return This builder.
      */
    public RetrievalResult.Builder setRepositoryId(String value) {
      validate(fields()[0], value);
      this.repository_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'repository_id' field has been set.
      * @return True if the 'repository_id' field has been set, false otherwise.
      */
    public boolean hasRepositoryId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'repository_id' field.
      * @return This builder.
      */
    public RetrievalResult.Builder clearRepositoryId() {
      repository_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'similar_faces' field.
      * @return The value.
      */
    public java.util.List<SimilarFace> getSimilarFaces() {
      return similar_faces;
    }

    /**
      * Sets the value of the 'similar_faces' field.
      * @param value The value of 'similar_faces'.
      * @return This builder.
      */
    public RetrievalResult.Builder setSimilarFaces(java.util.List<SimilarFace> value) {
      validate(fields()[1], value);
      this.similar_faces = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'similar_faces' field has been set.
      * @return True if the 'similar_faces' field has been set, false otherwise.
      */
    public boolean hasSimilarFaces() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'similar_faces' field.
      * @return This builder.
      */
    public RetrievalResult.Builder clearSimilarFaces() {
      similar_faces = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public RetrievalResult build() {
      try {
        RetrievalResult record = new RetrievalResult();
        record.repository_id = fieldSetFlags()[0] ? this.repository_id : (String) defaultValue(fields()[0]);
        record.similar_faces = fieldSetFlags()[1] ? this.similar_faces : (java.util.List<SimilarFace>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
